export enum EventType {
    COURSE_SYLLABUS_VIEW = "COURSE_SYLLABUS_VIEW",
    LOCK_CLICK = "LOCK_BUTTON_CLICK",
    TALK_TO_CLICK = "TALK_TO_CLICK",
    NOT_SURE_CLICK = "NOT_SURE_CLICK",
    REQUEST_A_CALLBACK_CLICK = "REQUEST_A_CALLBACK_CLICK",
    FORM_HOME = "FORM_HOME",
}